name: Multi Platform Testing

on:
  pull_request:


jobs:

  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS Info
        run: uname -a

      - name: Create File
        run: |
          echo "Hello from Ubuntu" > ubuntu.txt
          cat ubuntu.txt

  windows-job:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS Info
        run: systeminfo

      - name: Create File
        run: |
          echo Hello from Windows > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS Info
        run: uname -a

      - name: Create File
        run: |
          echo "Hello from macOS" > macos.txt
          cat macos.txt